new plugin API update
eclipse-zenoh/zenoh-plugin-dds pull request #168
Opened 2023-12-05 15:57 UTC by milyin

Update according to https://github.com/eclipse-zenoh/zenoh/pull/583

2024-01-30 10:43 UTC, JEnoch requested changes

2024-01-30 10:43 UTC, JEnoch commented on README.md
I suggest to further simplify this paragraph it instructing to just run `cargo build --release` (without `-p ...`) and describing the 2 resulting artifacts (lib plugin and bridge exe).

2024-01-30 10:43 UTC, JEnoch commented on zenoh-plugin-dds/src/lib.rs
Should the call to `declare_plugin!()` have a `#[cfg(feature = "no_mangle")]` as in https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/51 ?

2024-02-22 12:35 UTC, milyin commented on zenoh-plugin-dds/src/lib.rs
Fixed. Added issue about this for further investigation https://github.com/eclipse-zenoh/zenoh/issues/751

2024-02-22 13:12 UTC, merged

2024-02-22 13:36 UTC, milyin commented on README.md
done