Only access peer arg if mode is set to "peer"
eclipse-zenoh/zenoh-plugin-dds pull request #17
Opened 2020-11-25 17:12 UTC by spiderkeys

Running dzd with the default command line options leads to a panic
```
$ RUST_BACKTRACE=1 LD_LIBRARY_PATH=/usr/local/lib/ ./target/release/dzd 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/dzd.rs:43:63
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:50:5
   3: dzd::main::main::{{closure}}
   4: dzd::main
```
due to the line
```rust
config.insert("ZN_PEER_KEY".into(), args.value_of("peer").unwrap().into());
```
as `args.value_of("peer")` returns None, since mode defaults to "client".

This PR adds a simple check to prevent access of the peer arg, unless mode is set to "peer".

_Disclaimer: I'm a very novice Rustacean, so there is likely a better way to do this check_ :slightly_smiling_face:

2020-11-25 22:18 UTC, kydos requested changes
The match should operate on the Option as opposed to unwrap it as unwrapping None will fail (See https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap)

match args.value_of("mode") {
         Some("peer") => { config.insert("ZN_PEER_KEY".into(), args.value_of("peer").unwrap().into()); },
         None => {},
     }

2020-11-26 01:58 UTC, spiderkeys commented
Thanks for the note on matching on the Option input.

Regarding the client configuration, it seemed like what the original code was trying to do was insert the peer locator (specified by -e or --peer=<value>) into the ZN_PEER_KEY map entry. There is no --client arg to parse a locator from, so what config key needs info stored in it, and what info?

2020-11-27 11:31 UTC, kydos commented
@spiderkeys, I've updated the comment above. The only applicable comment is not the unwrap. As I see that there are still some issues with the ECA I'll push the fix. Thanks.

2020-11-27 11:44 UTC, kydos commented
I've pushed the fix thus I am closing this pull request.

2020-11-27 11:44 UTC, closed without merging