Update to new plugin system
eclipse-zenoh/zenoh-plugin-dds pull request #38
Opened 2021-07-19 12:22 UTC by p-avital

Update depends on PR [zenoh#121](https://github.com/eclipse-zenoh/zenoh/pull/121)

2021-07-19 16:52 UTC, p-avital commented
`Cargo.lock`'s version of zenoh isn't up to date, it still fetches pre [zenoh#121](https://github.com/eclipse-zenoh/zenoh/pull/121 ) versions, thus the compile error

2021-07-20 10:03 UTC, p-avital commented
Jenkinsfile and Dockerfile are now broken, but everything else is good :)

2021-07-20 10:11 UTC, JEnoch requested changes

2021-07-20 10:11 UTC, JEnoch commented on zplugin-dds/Cargo.toml
> +zenoh-plugin-rest = { git = "https://github.com/eclipse-zenoh/zenoh", default-features = false }
The zplugin-dds lib shouldn't depend on REST plugin.
Only the standalone bin does.

2021-07-20 16:54 UTC, JEnoch approved these changes

2021-07-20 17:03 UTC, merged